CREATE TABLE plants_table (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	plant_name TEXT NOT NULL,
	water_week INTEGER,
	water_day INTEGER,
	when_repot TEXT,
	fert_type TEXT,
	maint_level TEXT,
	rec_env TEXT,
	fun_fact TEXT,
	fav Boolean,
	date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

